### ISSUE TITLE
Max range number excluded

### ISSUE THREAD

**Issue by sketchthat** [NdT3Development/nodejs-random-number-between#1]
As per the example; https://github.com/NdT3Development/nodejs-random-number-between/blob/master/example.js

The `min` number is included in the range, but the `max` number is excluded.

`var rand = randnum(1, 10, 5);`

This request should generate `rand >= 1 && rand <= 10` however it doesn't include 10, instead making it `rand >= 1 && rand < 10`.

**Comment by TrueWinter** [comment]
Thanks! The pull request associated with this issue has been merged.
